/* Dahlman Dashboard — consolidated runtime
   Contains the former v4, v5, v8 and v9 modules plus the current home and gym enhancements. */

(()=>{
const V4_COLORS=['#ff4b52','#5aa9ff','#71d99b','#f6c85f','#a78bfa','#ff8c42','#4dd0e1','#f472b6','#94d82d','#c084fc','#38bdf8','#fb7185','#facc15'];
data.daysSince=Array.isArray(data.daysSince)?data.daysSince:[];
data.budget=(data.budget||[]).map(x=>({...x,category:x.category||'',notes:x.notes||'',fixed:Boolean(x.fixed)}));
const oldMergeData=mergeData;
mergeData=function(a,b){const out=oldMergeData(a,b);const map=new Map([...(a.daysSince||[]),...(b.daysSince||[])].map(x=>[x.id,x]));out.daysSince=[...map.values()];out.budget=(out.budget||[]).map(x=>({...x,category:x.category||'',notes:x.notes||'',fixed:Boolean(x.fixed)}));return out};
const snusCard=document.querySelector('.card.snus');
if(snusCard){snusCard.classList.remove('snus');snusCard.innerHTML='<div class="head"><div><small>CALENDAR</small><h3>Days since</h3></div><button data-go="dates" class="link">View all</button></div><div id="homeDaysSince" class="empty">No days-since counters yet.</div>'}
renderSnus=function(){};
const calendarActions=document.querySelector('#dates .actions');
if(calendarActions&&!document.getElementById('newDaysSinceBtn'))calendarActions.insertAdjacentHTML('beforeend','<button id="newDaysSinceBtn" class="primary" data-modal="daysSinceModal">+ Days since</button>');
if(!document.getElementById('daysSinceModal'))document.body.insertAdjacentHTML('beforeend',`<dialog id="daysSinceModal"><form id="daysSinceForm"><div class="modal-head"><h3>New days-since counter</h3><button type="button" data-close>×</button></div><label>Title<input name="title" required></label><label>Start date<input name="date" type="date" required></label><div class="form-actions"><button type="button" data-close>Cancel</button><button class="primary">Save</button></div></form></dialog>`);
const daysSinceForm=document.getElementById('daysSinceForm');
daysSinceForm.onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target).entries());data.daysSince.push({id:crypto.randomUUID(),...v});e.target.reset();e.target.closest('dialog').close();save('Days-since counter added')};
function nextEventDate(x){const base=new Date(x.date+'T12:00:00');if(!(x.recurring||x.type==='Birthday'))return base;const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate(),12);let next=new Date(now.getFullYear(),base.getMonth(),base.getDate(),12);if(next<today)next.setFullYear(next.getFullYear()+1);return next}
function dateDiff(d){return Math.ceil((d-new Date(new Date().toDateString()))/86400000)}
let editingNoteId=null;
renderNotes=function(){$('noteList').innerHTML=data.notes.length?[...data.notes].sort((a,b)=>(b.updated||b.created||'').localeCompare(a.updated||a.created||'')).map(x=>`<article class="note-card"><div class="note-actions"><button class="outline edit-note" data-edit-note="${x.id}">Edit</button><button class="delete" data-del-note="${x.id}">×</button></div><small>Updated ${fmt((x.updated||x.created||new Date().toISOString()).slice(0,10))}</small><h3>${esc(x.title)}</h3><p>${esc(x.content)}</p></article>`).join(''):'<p class="empty">No notes yet.</p>'};
$('noteForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target).entries()),now=new Date().toISOString();if(editingNoteId){const n=data.notes.find(x=>x.id===editingNoteId);if(n)Object.assign(n,v,{updated:now});editingNoteId=null;save('Note updated')}else{data.notes.push({id:crypto.randomUUID(),...v,created:now,updated:now});save('Note saved')}e.target.reset();e.target.closest('dialog').close()};
const budgetToolbar=document.querySelector('#budget .toolbar');if(budgetToolbar)budgetToolbar.querySelector('h2').textContent='Monthly budget';
const budgetForm=$('budgetForm');
if(budgetForm&&!budgetForm.querySelector('[name=category]')){budgetForm.querySelector('[name=title]').closest('label').insertAdjacentHTML('afterend','<label>Category<input name="category" placeholder="Housing, salary, food..."></label>');budgetForm.querySelector('[name=date]').closest('label').insertAdjacentHTML('afterend','<label class="switch"><input name="fixed" type="checkbox"> Fixed every month</label><label>Comment<input name="notes"></label>')}
$('budgetForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target).entries());data.budget.push({id:crypto.randomUUID(),...v,amount:+v.amount||0,fixed:e.target.fixed.checked});e.target.reset();e.target.closest('dialog').close();save('Budget row added')};
function drawMultiChart(canvas,series){if(!canvas)return;const dpr=devicePixelRatio||1,w=canvas.clientWidth||700,h=canvas.clientHeight||320;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);c.strokeStyle='rgba(255,255,255,.12)';c.lineWidth=1;for(let i=1;i<5;i++){c.beginPath();c.moveTo(38,(h-34)*i/5);c.lineTo(w-12,(h-34)*i/5);c.stroke()}const all=series.flatMap(s=>s.points.map(p=>p.v));if(!all.length){c.fillStyle='#777780';c.font='14px system-ui';c.fillText('Not enough data yet',45,h/2);return}const min=Math.min(...all),max=Math.max(...all),range=Math.max(1,max-min);series.forEach((s,si)=>{const pts=s.points,X=i=>42+(w-60)*i/Math.max(1,pts.length-1),Y=v=>10+(h-38)*(max-v)/range;c.strokeStyle=V4_COLORS[si%V4_COLORS.length];c.lineWidth=2.5;c.beginPath();pts.forEach((p,i)=>i?c.lineTo(X(i),Y(p.v)):c.moveTo(X(i),Y(p.v)));c.stroke();pts.forEach((p,i)=>{c.fillStyle=V4_COLORS[si%V4_COLORS.length];c.beginPath();c.arc(X(i),Y(p.v),3,0,Math.PI*2);c.fill()})})}
renderCharts=function(){const allSeries=EX.map(name=>({name,points:data.workouts.flatMap(w=>(w.exercises||[]).filter(e=>e.name===name).map(e=>({d:w.date,v:workoutMetric(e,w.bodyweight)}))).filter(x=>x.v>0).sort((a,b)=>a.d.localeCompare(b.d))})).filter(s=>s.points.length);drawMultiChart($('exerciseChart'),allSeries);drawMultiChart($('homeProgressChart'),allSeries);const card=$('exerciseChart')?.closest('.card');if(card){const select=$('chartExercise');if(select)select.style.display='none';let legend=card.querySelector('.chart-legend');if(!legend){legend=document.createElement('div');legend.className='chart-legend';card.appendChild(legend)}legend.innerHTML=allSeries.map((s,i)=>`<span><i style="background:${V4_COLORS[i%V4_COLORS.length]}"></i>${esc(s.name)}</span>`).join('')||'<span>No exercise data yet</span>'}}
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-note]');if(edit){const n=data.notes.find(x=>x.id===edit.dataset.editNote);if(n){editingNoteId=n.id;$('noteForm').title.value=n.title;$('noteForm').content.value=n.content;$('noteModal').querySelector('.modal-head h3').textContent='Edit note';$('noteModal').showModal()}}const ds=e.target.closest('[data-del-days-since]');if(ds){data.daysSince=data.daysSince.filter(x=>x.id!==ds.dataset.delDaysSince);save('Deleted')}});
document.addEventListener('change',e=>{const field=e.target.closest('[data-budget-field]');if(field){const row=field.closest('[data-budget-row]'),entry=data.budget.find(x=>x.id===row?.dataset.budgetRow);if(entry){entry[field.dataset.budgetField]=field.type==='checkbox'?field.checked:field.dataset.budgetField==='amount'?(+field.value||0):field.value;save('Budget updated')}}});
const workoutForm=$('workoutForm');if(workoutForm)workoutForm.classList.add('workout-form-v4');
})();

(()=>{
function money(n){return (Number(n)||0).toLocaleString('en-NO',{minimumFractionDigits:2,maximumFractionDigits:2})+' kr'}
function budgetTotals(){const income=(data.budget||[]).filter(x=>x.type==='income').reduce((s,x)=>s+(+x.amount||0),0);const expense=(data.budget||[]).filter(x=>x.type==='expense').reduce((s,x)=>s+(+x.amount||0),0);return{income,expense,left:income-expense}}
function ensureBudgetSheet(){const page=document.getElementById('budget');if(!page)return;let sheet=document.getElementById('budgetExcel');if(!sheet){sheet=document.createElement('div');sheet.id='budgetExcel';sheet.className='budget-excel';page.appendChild(sheet)}return sheet}
function rows(type){return (data.budget||[]).filter(x=>x.type===type).map(x=>`<tr data-budget-excel-row="${x.id}"><td><input data-budget-excel-field="title" value="${esc(x.title||'')}" placeholder="Description"></td><td><input class="amount-input" type="number" min="0" step="0.01" data-budget-excel-field="amount" value="${+x.amount||0}"></td><td class="row-actions"><button type="button" data-budget-excel-delete="${x.id}" aria-label="Delete row">×</button></td></tr>`).join('')}
function renderBudgetExcel(){const sheet=ensureBudgetSheet();if(!sheet)return;const t=budgetTotals();sheet.innerHTML=`<section class="budget-excel-panel"><table><thead><tr><th colspan="3">EXPENSES</th></tr><tr class="subhead"><th>Description</th><th>Sum</th><th></th></tr></thead><tbody>${rows('expense')||'<tr><td colspan="3"><input disabled value="No expense rows yet"></td></tr>'}</tbody><tfoot><tr><th>Total</th><td class="total-value">${money(t.expense)}</td><td></td></tr></tfoot></table><div class="budget-sheet-actions"><button type="button" class="primary" data-add-budget-row="expense">+ Add expense row</button></div><p class="budget-help">Click directly in any cell to edit. Changes save automatically.</p></section><section class="budget-excel-panel"><table><thead><tr><th colspan="3">INCOME</th></tr><tr class="subhead"><th>Description</th><th>Sum</th><th></th></tr></thead><tbody>${rows('income')||'<tr><td colspan="3"><input disabled value="No income rows yet"></td></tr>'}</tbody><tfoot><tr><th>Total income</th><td class="total-value">${money(t.income)}</td><td></td></tr></tfoot></table><div class="budget-summary-box"><table><thead><tr><th>LEFT OVER</th></tr></thead><tbody><tr><td class="left-value">${money(t.left)}</td></tr></tbody></table></div><div class="budget-sheet-actions"><button type="button" class="primary" data-add-budget-row="income">+ Add income row</button></div></section>`}
const oldRenderBudget=renderBudget;renderBudget=function(){oldRenderBudget();renderBudgetExcel()};
document.addEventListener('click',e=>{const add=e.target.closest('[data-add-budget-row]');if(add){data.budget.push({id:crypto.randomUUID(),title:'',type:add.dataset.addBudgetRow,amount:0,date:day(),category:'',notes:'',fixed:true});save('Budget row added');setTimeout(()=>{const inputs=document.querySelectorAll(`[data-budget-excel-row] input[data-budget-excel-field="title"]`);inputs[inputs.length-1]?.focus()},50)}const del=e.target.closest('[data-budget-excel-delete]');if(del){data.budget=data.budget.filter(x=>x.id!==del.dataset.budgetExcelDelete);save('Budget row deleted')}});
document.addEventListener('change',e=>{const f=e.target.closest('[data-budget-excel-field]');if(!f)return;const row=f.closest('[data-budget-excel-row]'),entry=data.budget.find(x=>x.id===row?.dataset.budgetExcelRow);if(!entry)return;entry[f.dataset.budgetExcelField]=f.dataset.budgetExcelField==='amount'?(+f.value||0):f.value;save('Budget updated')});
renderBudgetExcel();
})();

(()=>{
'use strict';
const LOGO='/assets/icon-192-ivory.png?v=11',LOGO_FALLBACK='/assets/dahlmans-logo-192.png?v=11';
const PHOTOS=Array.from({length:9},(_,i)=>`/assets/background-${String(i+1).padStart(2,'0')}.jpg`),PAGE_TITLE='Welcome Janelle';
function ensureHead(){document.title=PAGE_TITLE;const upsert=(rel,href,type)=>{let el=document.querySelector(`link[rel="${rel}"]`);if(!el){el=document.createElement('link');el.rel=rel;document.head.appendChild(el)}el.href=href;if(type)el.type=type};upsert('icon','/assets/favicon.ico?v=11','image/x-icon');upsert('apple-touch-icon','/assets/icon-192-ivory.png?v=11','image/png');upsert('manifest','/manifest.json?v=11')}
function ensureDaily(){data.daily=Array.isArray(data.daily)?data.daily:[];const title='Wash face',found=data.daily.find(x=>String(x.title||'').trim().toLowerCase()==='wash face');if(found){found.id='daily-wash-face';found.title=title}else data.daily.push({id:'daily-wash-face',title})}
function brand(){const b=document.querySelector('.brand');if(b){b.innerHTML=`<img class="brand-logo" src="${LOGO}" alt="Dahlmans Verksted"><span><strong>Janelle Dashboard</strong></span>`;const img=b.querySelector('.brand-logo');if(img)img.onerror=()=>{if(!img.dataset.fallback){img.dataset.fallback='1';img.src=LOGO_FALLBACK}}}const calc=document.querySelector('.nav[data-page="calculator"] span');if(calc)calc.textContent='Dahlmans Verksted';const title=document.getElementById('title');if(title)title.textContent=''}
function removeQuickAdd(){document.getElementById('quick')?.remove()}
function mergeDateIntoWeather(){const today=document.getElementById('today'),world=document.querySelector('#dashboard .world-widget'),textWrap=world?.querySelector('.head>div');if(!today||!textWrap)return;today.classList.add('world-date');if(today.parentElement!==textWrap)textWrap.insertBefore(today,textWrap.querySelector('h3')||null);const eyebrow=textWrap.querySelector('small');if(eyebrow)eyebrow.textContent='DATE · TIME · WEATHER';const heading=textWrap.querySelector('h3');if(heading)heading.textContent='Norway and Philippines'}
function mergeCalendarWidgets(){const daysCard=document.querySelector('#dashboard .card:not(.unified-calendar):has(#homeDaysSince)')||document.querySelector('#dashboard .card.snus'),countdown=document.getElementById('nextCountdown'),countdownCard=countdown?.closest('article.card');if(!daysCard||!countdown||!countdownCard||daysCard===countdownCard)return;const head=daysCard.querySelector(':scope>.head');if(!head)return;daysCard.classList.add('v8-calendar-combined');const eyebrow=head.querySelector('small'),heading=head.querySelector('h3');if(eyebrow)eyebrow.textContent='CALENDAR';if(heading)heading.textContent='Calendar';let viewAll=head.querySelector('[data-go="dates"]');if(!viewAll){viewAll=countdownCard.querySelector('[data-go="dates"]');if(viewAll)head.appendChild(viewAll)}let grid=daysCard.querySelector(':scope>.v8-calendar-combined-grid');if(!grid){grid=document.createElement('div');grid.className='v8-calendar-combined-grid';const daysPart=document.createElement('section');daysPart.className='v8-calendar-part v8-calendar-days';daysPart.innerHTML='<h4 class="v8-calendar-part-title">Days since</h4>';[...daysCard.children].filter(el=>el!==head&&el!==grid).forEach(el=>daysPart.appendChild(el));const countdownPart=document.createElement('section');countdownPart.className='v8-calendar-part v8-calendar-countdown';countdownPart.innerHTML='<h4 class="v8-calendar-part-title">Next countdown</h4>';countdownPart.appendChild(countdown);grid.append(daysPart,countdownPart);daysCard.appendChild(grid)}countdownCard.remove()}
function ensureCarousel(){const page=document.getElementById('dashboard'),hero=page?.querySelector('.hero');if(!page||!hero)return;const heroTitle=hero.querySelector('h2');if(heroTitle)heroTitle.textContent='Welcome';let wrap=page.querySelector('.v8-home-top');if(!wrap){wrap=document.createElement('div');wrap.className='v8-home-top';hero.parentNode.insertBefore(wrap,hero);wrap.appendChild(hero)}let carousel=wrap.querySelector('.v8-carousel');if(!carousel){carousel=document.createElement('section');carousel.className='v8-carousel';carousel.innerHTML='<img alt="Our moments" class="active"><img alt="Our moments"><span>OUR MOMENTS</span>';wrap.appendChild(carousel);let idx=0,layer=0;const imgs=[...carousel.querySelectorAll('img')];imgs[0].src=PHOTOS[0];imgs[1].src=PHOTOS[1];PHOTOS.forEach(src=>{const i=new Image();i.src=src});setInterval(()=>{const next=(idx+1)%PHOTOS.length,incoming=imgs[1-layer],outgoing=imgs[layer];incoming.src=PHOTOS[next]+'?v=11';incoming.onload=()=>{incoming.classList.add('active');outgoing.classList.remove('active');idx=next;layer=1-layer}},12000)}}
function mobileMenu(){document.querySelectorAll('.legacy-bottom-nav,.bottom-nav,#bottomNav').forEach(x=>x.remove());if(document.getElementById('v8MenuBtn'))return;const btn=document.createElement('button');btn.id='v8MenuBtn';btn.className='v8-menu-btn';btn.type='button';btn.textContent='☰';btn.setAttribute('aria-label','Open menu');const menu=document.createElement('div');menu.id='v8MobileMenu';menu.className='v8-mobile-menu';document.querySelectorAll('aside nav .nav[data-page]').forEach(n=>{const x=document.createElement('button');x.type='button';x.dataset.page=n.dataset.page;x.innerHTML=n.innerHTML;x.onclick=()=>{n.click();menu.classList.remove('open');btn.textContent='☰'};menu.appendChild(x)});btn.onclick=()=>{const o=menu.classList.toggle('open');btn.textContent=o?'×':'☰'};document.body.append(btn,menu)}
function equalBudget(){const grid=document.getElementById('budgetExcel');if(!grid)return;grid.classList.add('v8-budget-grid');const panels=[...grid.children];if(panels.length>1){panels[0].classList.add('expense-panel');panels[1].classList.add('income-panel')}}
function removeDuplicateNav(){document.querySelectorAll('body>nav,main+nav,.mobile-bottom-nav').forEach(el=>{if(!el.closest('aside'))el.remove()})}
function apply(){ensureHead();ensureDaily();brand();removeQuickAdd();ensureCarousel();mergeDateIntoWeather();mergeCalendarWidgets();mobileMenu();equalBudget();removeDuplicateNav()}
window.dashboardChromeApply=apply;
})();

(()=>{
'use strict';
const DAY_MS=86400000,startOfToday=()=>{const n=new Date();return new Date(n.getFullYear(),n.getMonth(),n.getDate(),12)},safeDate=s=>new Date(`${s}T12:00:00`),wholeDaysBetween=(a,b)=>Math.max(0,Math.floor((b-a)/DAY_MS));
const nextAnnualDate=s=>{const birth=safeDate(s),today=startOfToday();let next=new Date(today.getFullYear(),birth.getMonth(),birth.getDate(),12);if(next<today)next.setFullYear(next.getFullYear()+1);return next};
const ageOnDate=(birth,today=startOfToday())=>{let age=today.getFullYear()-birth.getFullYear();const before=today.getMonth()<birth.getMonth()||(today.getMonth()===birth.getMonth()&&today.getDate()<birth.getDate());return age-(before?1:0)},detail=(label,value,extra='')=>`<div class="v9-detail-row ${extra}"><span>${label}</span><b>${value}</b></div>`;
function birthdayCard(x){const birth=safeDate(x.date),today=startOfToday(),next=nextAnnualDate(x.date),age=Math.max(0,ageOnDate(birth,today)),lived=wholeDaysBetween(birth,today).toLocaleString('en-GB'),until=Math.max(0,Math.ceil((next-today)/DAY_MS)).toLocaleString('en-GB');return `<article class="date-card v9-date-card birthday-card"><button class="delete" data-del-date="${x.id}">×</button><div class="v9-date-details">${detail('Date:',fmt(x.date))}${detail('Age:',`${age} years`)}${detail('Days lived:',lived)}${detail('Next birthday:',`${until} days`)}${detail('Name:',esc(x.title),'v9-name')}</div><p class="v9-card-kind">Birthday</p></article>`}
function standardDateCard(x){const recurring=x.recurring||x.type==='Birthday',next=recurring?nextAnnualDate(x.date):safeDate(x.date),remaining=Math.ceil((next-startOfToday())/DAY_MS),timing=remaining>=0?`${remaining.toLocaleString('en-GB')} days remaining`:`${Math.abs(remaining).toLocaleString('en-GB')} days ago`;return `<article class="date-card v9-date-card"><button class="delete" data-del-date="${x.id}">×</button><div class="v9-date-details">${detail('Date:',fmt(x.date))}${detail('Status:',timing)}${detail('Name:',esc(x.title),'v9-name')}</div><p class="v9-card-kind">${esc(x.type||'Date')}</p></article>`}
function countdownCard(x){const n=daysTo(x.date);return `<article class="date-card v9-date-card countdown-card"><button class="delete" data-del-countdown="${x.id}">×</button><div class="v9-date-details">${detail('Date:',fmt(x.date))}${detail('Days remaining:',Math.max(0,n).toLocaleString('en-GB'))}${detail('Name:',esc(x.title),'v9-name')}</div><p class="v9-card-kind">Countdown</p></article>`}
function daysSinceCard(x){const n=Math.max(0,-daysTo(x.date));return `<article class="date-card v9-date-card since-card"><button class="delete" data-del-days-since="${x.id}">×</button><div class="v9-date-details">${detail('Date:',fmt(x.date))}${detail('Days since:',n.toLocaleString('en-GB'))}${detail('Name:',esc(x.title),'v9-name')}</div><p class="v9-card-kind">Days since</p></article>`}
function renderDatesV9(){const daysSince=Array.isArray(data.daysSince)?data.daysSince:[],calendar=[...(data.dates||[]).map(x=>({...x,kind:'date'})),...(data.countdowns||[]).map(x=>({...x,kind:'countdown'})),...daysSince.map(x=>({...x,kind:'daysSince'}))].sort((a,b)=>a.date.localeCompare(b.date));$('dateList').innerHTML=calendar.length?calendar.map(x=>x.kind==='daysSince'?daysSinceCard(x):x.kind==='countdown'?countdownCard(x):x.type==='Birthday'?birthdayCard(x):standardDateCard(x)).join(''):'<p class="empty">No dates, countdowns or days-since counters yet.</p>';const upcoming=(data.dates||[]).map(x=>({x,d:(x.recurring||x.type==='Birthday')?nextAnnualDate(x.date):safeDate(x.date)})).filter(v=>v.d>=startOfToday()).sort((a,b)=>a.d-b.d)[0];$('nextDate').innerHTML=upcoming?dateBox(upcoming.x.title,upcoming.d.toISOString().slice(0,10)):'<p class="empty">No upcoming dates.</p>';const c=(data.countdowns||[]).filter(x=>daysTo(x.date)>=0).sort((a,b)=>a.date.localeCompare(b.date))[0];$('nextCountdown').innerHTML=c?`<div class="countdown-big"><b>${daysTo(c.date)}</b><div><h3>${esc(c.title)}</h3><p>days remaining</p></div></div>`:'<p class="empty">No countdowns yet.</p>';const since=[...daysSince].sort((a,b)=>a.date.localeCompare(b.date))[0],home=document.getElementById('homeDaysSince');if(home)home.innerHTML=since?`<div class="countdown-big"><b>${Math.max(0,-daysTo(since.date))}</b><div><h3>${esc(since.title)}</h3><p>days since ${fmt(since.date)}</p></div></div>`:'<p class="empty">No days-since counters yet.</p>'}
renderDates=renderDatesV9;
window.renderDatesUnified=renderDatesV9;
})();

(()=>{
'use strict';
function homeLayout(){const grid=document.querySelector('#dashboard>.grid');if(!grid)return;const cards=[...grid.children],focus=cards.find(x=>x.querySelector('#priority')),daily=cards.find(x=>x.querySelector('#dailyList')),calendar=cards.find(x=>x.classList.contains('v8-calendar-combined'))||cards.find(x=>x.querySelector('#homeDaysSince')),progress=cards.find(x=>x.querySelector('#homeProgressChart')),nextDate=cards.find(x=>x.querySelector('#nextDate')),countdown=cards.find(x=>x.querySelector('#nextCountdown'));if(nextDate&&nextDate!==calendar)nextDate.remove();if(countdown&&countdown!==calendar)countdown.remove();if(calendar){calendar.classList.add('unified-calendar');const title=calendar.querySelector('.head h3');if(title)title.textContent='Calendar';const eye=calendar.querySelector('.head small');if(eye)eye.textContent='CALENDAR'}[focus,daily,calendar,progress].filter(Boolean).forEach(x=>grid.appendChild(x))}
const MUSCLES={'Bench Press':'Chest','Incline Dumbbell Press':'Chest','Tricep Cable Pushdown':'Triceps','Overhead Extension Bumper':'Triceps','Cable Pressdown':'Triceps','Pullups':'Back','Cable Row':'Back','Bicep Cable Curl':'Biceps','Bicep Barbell Curl':'Biceps','Bicep Dumbbell Curl':'Biceps','Cable Curl':'Biceps','Lateral Raise':'Shoulders','Overhead Barbell Press':'Shoulders'},COLORS=['#d8b08b','#9b6944','#c89b73','#6f8f7b','#8090a8','#b47f78','#8d7ca8'];
function muscleData(){const totals={};(data.workouts||[]).forEach(w=>(w.exercises||[]).forEach(e=>{const group=MUSCLES[e.name]||'Other',sets=Math.max(1,(e.sets||[]).length);totals[group]=(totals[group]||0)+sets}));return Object.entries(totals).sort((a,b)=>b[1]-a[1])}
function ensureMuscleChart(){const page=document.getElementById('training'),progress=document.getElementById('exerciseChart')?.closest('.card');if(!page||!progress)return;let card=document.getElementById('muscleGroupCard');if(!card){card=document.createElement('article');card.id='muscleGroupCard';card.className='card muscle-card';card.innerHTML='<div class="head"><div><small>MUSCLE BALANCE</small><h3>Most trained muscle groups</h3></div></div><div class="muscle-chart-wrap"><canvas id="muscleGroupChart" width="420" height="420"></canvas><div id="muscleLegend" class="muscle-legend"></div></div>';progress.insertAdjacentElement('afterend',card)}drawMuscleChart()}
function drawMuscleChart(){const canvas=document.getElementById('muscleGroupChart'),legend=document.getElementById('muscleLegend');if(!canvas||!legend)return;const entries=muscleData(),dpr=devicePixelRatio||1,size=Math.min(canvas.clientWidth||360,420);canvas.width=size*dpr;canvas.height=size*dpr;const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,size,size);const total=entries.reduce((s,x)=>s+x[1],0),cx=size/2,cy=size/2,r=size*.39,inner=r*.57;if(!total){c.fillStyle='rgba(216,176,139,.12)';c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fill();c.fillStyle='#b8aea4';c.textAlign='center';c.font='14px Poppins';c.fillText('No workout data yet',cx,cy);legend.innerHTML='';return}let angle=-Math.PI/2;entries.forEach(([name,value],i)=>{const slice=value/total*Math.PI*2;c.beginPath();c.moveTo(cx,cy);c.arc(cx,cy,r,angle,angle+slice);c.closePath();c.fillStyle=COLORS[i%COLORS.length];c.fill();angle+=slice});c.globalCompositeOperation='destination-out';c.beginPath();c.arc(cx,cy,inner,0,Math.PI*2);c.fill();c.globalCompositeOperation='source-over';c.fillStyle='#f7f3ee';c.textAlign='center';c.font='500 27px Poppins';c.fillText(String(total),cx,cy-2);c.fillStyle='#b8aea4';c.font='11px Poppins';c.fillText('total sets',cx,cy+20);legend.innerHTML=entries.map(([name,value],i)=>`<div><i style="background:${COLORS[i%COLORS.length]}"></i><span>${name}</span><b>${Math.round(value/total*100)}%</b></div>`).join('')}
function apply(){window.dashboardChromeApply?.();window.renderDatesUnified?.();const dateGrid=document.getElementById('dateList');if(dateGrid)dateGrid.classList.add('v9-date-grid');const workoutList=document.getElementById('workoutList');if(workoutList)workoutList.classList.add('v9-workout-grid');homeLayout();ensureMuscleChart()}
const originalRender=render;render=function(){const result=originalRender.apply(this,arguments);requestAnimationFrame(apply);return result};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>requestAnimationFrame(apply));else requestAnimationFrame(apply);
new MutationObserver(()=>{clearTimeout(window.__unifiedTimer);window.__unifiedTimer=setTimeout(apply,80)}).observe(document.body,{childList:true,subtree:true});
addEventListener('resize',()=>{clearTimeout(window.__muscleResize);window.__muscleResize=setTimeout(drawMuscleChart,120)});
render();setTimeout(apply,400);setTimeout(apply,1600);
})();
