const KEY='janelle_dashboard_v1';
const EX=['Bench Press','Incline Dumbbell Press','Tricep Cable Pushdown','Overhead Extension Bumper','Pullups','Bicep Cable Curl','Bicep Barbell Curl','Bicep Dumbbell Curl','Lateral Raise','Cable Curl','Cable Pressdown','Cable Row','Overhead Barbell Press'];
const DAILY=['Brush teeth','Tell Janelle she is beautiful','Eat enough protein','Exercise','Do something productive'];
const DEFAULT={daily:DAILY.map((title,i)=>({id:'daily-'+i,title})),dailyDone:{},tasks:[],workouts:[],dates:[],countdowns:[],shoppingLists:[],notes:[],budget:[],snusStart:'2026-07-05'};
let data=migrate(load()),filter='all',saveTimer=null,lastUpdated='';
const $=id=>document.getElementById(id), day=()=>new Date().toISOString().slice(0,10), esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||JSON.parse(localStorage.getItem('dahlman_dashboard_v2'))||clone(DEFAULT)}catch{return clone(DEFAULT)}}
function migrate(x){const d={...clone(DEFAULT),...(x||{})};d.daily=clone(DEFAULT.daily);d.dailyDone=d.dailyDone||{};d.tasks=d.tasks||[];d.workouts=(d.workouts||[]).map(w=>({...w,exercises:Array.isArray(w.exercises)?w.exercises:[]}));d.dates=d.dates||[];d.countdowns=d.countdowns||[];d.shoppingLists=(d.shoppingLists||[]).map(l=>({...l,items:l.items||[]}));d.notes=d.notes||[];d.budget=d.budget||[];return d}
function mergeData(a,b){const out=migrate({...a,...b});for(const key of ['tasks','workouts','dates','countdowns','shoppingLists','notes','budget']){const map=new Map([...(a[key]||[]),...(b[key]||[])].map(x=>[x.id,x]));out[key]=[...map.values()]}out.dailyDone={...(a.dailyDone||{}),...(b.dailyDone||{})};return out}
async function api(method='GET',body){const r=await fetch('/api/state',{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});if(r.status===404)return null;if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function initSync(){try{const remote=await api();if(remote?.data){data=mergeData(data,remote.data);lastUpdated=remote.updatedAt||''}await push();$('cloudStatus').textContent='Shared sync';$('cloudStatus').className='cloud-status online'}catch(e){console.error(e);$('cloudStatus').textContent='Offline';$('cloudStatus').className='cloud-status error'}setInterval(pull,5000)}
async function pull(){try{const remote=await api();if(remote?.data&&remote.updatedAt!==lastUpdated){data=mergeData(data,remote.data);lastUpdated=remote.updatedAt||'';localStorage.setItem(KEY,JSON.stringify(data));render()}}catch(e){console.error(e)}}
async function push(){try{const r=await api('PUT',{data});lastUpdated=r?.updatedAt||lastUpdated;$('cloudStatus').textContent='Shared sync'}catch(e){console.error(e);$('cloudStatus').textContent='Sync failed'}}
function save(msg){localStorage.setItem(KEY,JSON.stringify(data));render();clearTimeout(saveTimer);saveTimer=setTimeout(push,350);if(msg)toast(msg)}
function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
function fmt(s,opt={day:'numeric',month:'short',year:'numeric'}){return s?new Date(s+'T12:00:00').toLocaleDateString('en-GB',opt):''}
function daysTo(s){return Math.ceil((new Date(s+'T12:00:00')-new Date(new Date().toDateString()))/86400000)}
function nav(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===p));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));const names={dashboard:'Welcome Mr. and Mrs. Dahlman',training:"Vgor's Gym",tasks:'To do list',dates:'Calendar & Countdowns',shopping:'Shoppinglist',calculator:'Flowerbox calculator',statistics:'Statistics',budget:'Budget',notes:'Notes'};$('title').textContent=names[p]||'Dashboard';if(p==='training')setTimeout(renderCharts,20);scrollTo({top:0,behavior:'smooth'})}
function renderDaily(){const k=day(),done=data.dailyDone[k]||[];$('dailyList').innerHTML=data.daily.map(x=>`<label class="check ${done.includes(x.id)?'done':''}"><input type="checkbox" data-daily="${x.id}" ${done.includes(x.id)?'checked':''}><span>${esc(x.title)}</span></label>`).join('');$('dailyProgress').style.width=(done.length/data.daily.length*100)+'%';$('dailyCount').textContent=`${done.length}/${data.daily.length}`}
function renderTasks(){const ord={high:0,medium:1,low:2},arr=[...data.tasks].sort((a,b)=>Number(a.done)-Number(b.done)||ord[a.priority]-ord[b.priority]),show=arr.filter(x=>filter==='all'||(filter==='done'?x.done:!x.done));$('taskList').innerHTML=show.length?show.map(x=>`<article class="task ${x.done?'done':''}"><input type="checkbox" data-task="${x.id}" ${x.done?'checked':''}><div class="task-main"><h3>${esc(x.title)}</h3><p>${x.dueDate?'Due '+fmt(x.dueDate):'No due date'}${x.category?' · '+esc(x.category):''}</p></div><div><span class="tag ${x.priority}">${x.priority}</span><button class="delete" data-del-task="${x.id}">×</button></div></article>`).join(''):'<p class="empty">Nothing here.</p>';$('openCount').textContent=arr.filter(x=>!x.done).length;$('priority').innerHTML=arr.filter(x=>!x.done).slice(0,4).map(x=>`<div class="compact ${x.priority}"><i></i><div><b>${esc(x.title)}</b><span>${x.dueDate?fmt(x.dueDate):'No due date'}</span></div></div>`).join('')||'<p class="empty">Everything is done.</p>'}
function renderDates(){const all=[...data.dates.map(x=>({...x,kind:'date'})),...data.countdowns.map(x=>({...x,kind:'countdown'}))].sort((a,b)=>a.date.localeCompare(b.date));$('dateList').innerHTML=all.length?all.map(x=>{const n=daysTo(x.date);return`<article class="date-card ${x.kind==='countdown'?'countdown-card':''}"><button class="delete" data-del-${x.kind}="${x.id}">×</button><div class="date-line">${fmt(x.date)} · ${n>=0?n+' days remaining':(-n)+' days ago'}</div><h3>${esc(x.title)}</h3><p>${x.kind==='countdown'?'Countdown':esc(x.type||'Date')}</p>${x.kind==='countdown'?`<div class="countdown-big"><b>${Math.max(0,n)}</b><span>days</span></div>`:''}</article>`}).join(''):'<p class="empty">No dates or countdowns yet.</p>';const next=data.dates.filter(x=>daysTo(x.date)>=0).sort((a,b)=>a.date.localeCompare(b.date))[0];$('nextDate').innerHTML=next?dateBox(next.title,next.date):'<p class="empty">No upcoming dates.</p>';const c=data.countdowns.filter(x=>daysTo(x.date)>=0).sort((a,b)=>a.date.localeCompare(b.date))[0];$('nextCountdown').innerHTML=c?`<div class="countdown-big"><b>${daysTo(c.date)}</b><div><h3>${esc(c.title)}</h3><p>days remaining</p></div></div>`:'<p class="empty">No countdowns yet.</p>'}
function dateBox(title,date){return`<div class="datebox"><div class="badge"><b>${new Date(date+'T12:00:00').getDate()}</b><span>${new Date(date+'T12:00:00').toLocaleDateString('en-GB',{month:'short'})}</span></div><div><h3>${esc(title)}</h3><p>${daysTo(date)} days remaining</p></div></div>`}
function workoutMetric(e,bw){const vals=(e.sets||[]).map(s=>({w:String(s.weight).toUpperCase()==='BW'?+bw||0:+s.weight||0,r:+s.reps||0})).filter(s=>s.w&&s.r);return vals.length?Math.max(...vals.map(s=>s.w*(1+s.r/30))):0}
function renderWorkouts(){const arr=[...data.workouts].sort((a,b)=>b.date.localeCompare(a.date));$('totalWorkouts').textContent=arr.length;$('monthWorkouts').textContent=$('monthCount').textContent=arr.filter(x=>x.date.startsWith(day().slice(0,7))).length;$('latestWeight').textContent=arr.find(x=>x.bodyweight)?.bodyweight?arr.find(x=>x.bodyweight).bodyweight+' kg':'–';$('workoutList').innerHTML=arr.length?arr.map(w=>`<article class="workout"><div class="workout-top"><div><div class="workout-date">${fmt(w.date)}</div><h3>${esc(w.title)}</h3><p>${w.duration||0} min${w.bodyweight?' · '+w.bodyweight+' kg':''}</p></div><button class="delete" data-del-workout="${w.id}">×</button></div>${(w.exercises||[]).map(e=>`<div class="exercise-item"><b>${esc(e.name)}</b><span>${(e.sets||[]).map((s,i)=>`Set ${i+1}: ${esc(s.weight)} × ${s.reps}`).join(' · ')}</span></div>`).join('')}</article>`).join(''):'<p class="empty">No workouts logged.</p>';renderCharts()}
function drawChart(canvas,series){if(!canvas)return;const dpr=devicePixelRatio||1,w=canvas.clientWidth||700,h=canvas.clientHeight||260;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);c.strokeStyle='rgba(255,255,255,.12)';c.lineWidth=1;for(let i=1;i<5;i++){c.beginPath();c.moveTo(35,(h-30)*i/5);c.lineTo(w-10,(h-30)*i/5);c.stroke()}if(!series.length){c.fillStyle='#777780';c.font='14px system-ui';c.fillText('Not enough data yet',45,h/2);return}const vals=series.map(x=>x.v),min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min),X=i=>40+(w-55)*i/Math.max(1,series.length-1),Y=v=>10+(h-35)*(max-v)/range;c.strokeStyle='#ff4b52';c.lineWidth=3;c.beginPath();series.forEach((p,i)=>i?c.lineTo(X(i),Y(p.v)):c.moveTo(X(i),Y(p.v)));c.stroke();c.fillStyle='#ff4b52';series.forEach((p,i)=>{c.beginPath();c.arc(X(i),Y(p.v),4,0,Math.PI*2);c.fill()})}
function renderCharts(){const select=$('chartExercise');if(select&&!select.options.length)select.innerHTML=EX.map(x=>`<option>${x}</option>`).join('');const selected=select?.value||EX[0];const points=data.workouts.flatMap(w=>(w.exercises||[]).filter(e=>e.name===selected).map(e=>({d:w.date,v:workoutMetric(e,w.bodyweight)}))).filter(x=>x.v>0).sort((a,b)=>a.d.localeCompare(b.d));drawChart($('exerciseChart'),points);const grouped=[];for(const ex of EX.slice(0,5)){const p=data.workouts.flatMap(w=>(w.exercises||[]).filter(e=>e.name===ex).map(e=>({d:w.date,v:workoutMetric(e,w.bodyweight)}))).filter(x=>x.v>0).sort((a,b)=>a.d.localeCompare(b.d));if(p.length)grouped.push(p.at(-1))}drawChart($('homeProgressChart'),grouped)}
function renderShopping(){const lists=data.shoppingLists;$('shoppingLists').innerHTML=lists.length?lists.map(l=>`<article class="shopping-card"><div class="head"><div><small>SHOPPING LIST</small><h3>${esc(l.title)}</h3></div><div><button class="plus" data-add-shopping="${l.id}">+</button><button class="delete" data-del-shopping-list="${l.id}">×</button></div></div><div class="shopping-items">${l.items.length?l.items.map(i=>`<label class="check ${i.done?'done':''}"><input type="checkbox" data-shopping-item="${i.id}" data-list-id="${l.id}" ${i.done?'checked':''}><span>${esc(i.title)}</span><button class="delete" data-del-shopping-item="${i.id}" data-list-id="${l.id}">×</button></label>`).join(''):'<p class="empty">No items yet.</p>'}</div></article>`).join(''):'<p class="empty">Create your first shopping list.</p>'}
function renderNotes(){$('noteList').innerHTML=data.notes.length?data.notes.map(x=>`<article class="note-card"><button class="delete" data-del-note="${x.id}">×</button><small>${fmt(x.created?.slice(0,10)||day())}</small><h3>${esc(x.title)}</h3><p>${esc(x.content)}</p></article>`).join(''):'<p class="empty">No notes yet.</p>'}
function renderBudget(){const income=data.budget.filter(x=>x.type==='income').reduce((a,x)=>a+(+x.amount||0),0),expense=data.budget.filter(x=>x.type==='expense').reduce((a,x)=>a+(+x.amount||0),0);$('incomeTotal').textContent=Math.round(income).toLocaleString('no-NO')+' kr';$('expenseTotal').textContent=Math.round(expense).toLocaleString('no-NO')+' kr';$('budgetBalance').textContent=Math.round(income-expense).toLocaleString('no-NO')+' kr';$('budgetList').innerHTML=[...data.budget].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<article class="budget-row ${x.type}"><div><h3>${esc(x.title)}</h3><p>${fmt(x.date)}</p></div><span class="amount">${x.type==='expense'?'-':'+'}${(+x.amount).toLocaleString('no-NO')} kr</span><button class="delete" data-del-budget="${x.id}">×</button></article>`).join('')||'<p class="empty">No budget entries.</p>'}
function habitStats(){const days=Object.keys(data.dailyDone),total=Math.max(1,days.length);return data.daily.map(h=>{const n=days.filter(d=>(data.dailyDone[d]||[]).includes(h.id)).length;return{title:h.title,n,pct:Math.round(n/total*100)}})}
function renderStatistics(){const completed=data.tasks.filter(x=>x.done).length,days=Object.keys(data.dailyDone).length,habits=habitStats(),avg=days?Math.round(habits.reduce((a,x)=>a+x.pct,0)/habits.length):0;$('statisticsGrid').innerHTML=`<article class="stat-tile"><small>WORKOUTS</small><b>${data.workouts.length}</b></article><article class="stat-tile"><small>TASKS DONE</small><b>${completed}</b></article><article class="stat-tile"><small>DAILY AVG</small><b>${avg}%</b></article><article class="stat-tile"><small>BUDGET ENTRIES</small><b>${data.budget.length}</b></article>`;$('habitStats').innerHTML=habits.map(x=>`<div class="habit-stat"><b>${esc(x.title)}</b><div class="habit-bar"><i style="width:${x.pct}%"></i></div><span>${x.n}/${days||0} · ${x.pct}%</span></div>`).join('')}
function renderSnus(){const n=Math.max(0,Math.floor((new Date(new Date().toDateString())-new Date(data.snusStart+'T12:00:00'))/86400000));$('snusDays').textContent=n;$('snusSince').textContent='Since '+fmt(data.snusStart)}
function render(){ $('today').textContent=new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});renderSnus();renderDaily();renderTasks();renderDates();renderWorkouts();renderShopping();renderNotes();renderBudget();renderStatistics();calculateBox()}
function openModal(id){document.querySelectorAll('dialog[open]').forEach(x=>x.close());const d=$(id);if(id==='workoutModal'){d.querySelector('[name=date]').value=day();$('exerciseRows').innerHTML='';addExercise()}if(id==='budgetModal')d.querySelector('[name=date]').value=day();d.showModal()}
function addExercise(){const card=document.createElement('div');card.className='exercise-card';card.innerHTML=`<div class="exercise-head"><select class="exercise-name">${EX.map(x=>`<option>${x}</option>`).join('')}</select><button type="button" class="delete remove-exercise">×</button></div><div class="sets-v3"></div><div class="exercise-actions"><button type="button" class="outline add-set-v3">+ Set</button></div>`;$('exerciseRows').append(card);addSet(card.querySelector('.sets-v3'))}
function addSet(list){const row=document.createElement('div');row.className='set-row-v3';row.innerHTML=`<span>${list.children.length+1}</span><label>Weight<input class="weight" value="BW" inputmode="decimal"></label><label>Reps<input class="reps" type="number" min="0" value="0"></label><button type="button" class="delete remove-set-v3">×</button>`;list.append(row)}
function renumber(list){[...list.children].forEach((x,i)=>x.firstElementChild.textContent=i+1)}
function calculateBox(){const type=$('boxType')?.value||'slats',L=+$('boxL')?.value||0,B=+$('boxB')?.value||0,H=+$('boxH')?.value||0,S=+$('boxS')?.value||0;let rows,items=[];if(type==='slats'){rows=Math.max(0,Math.floor((H-2.3+S)/(4.8+S)));items=[['48×48 posts/support',4,Math.max(0,H-9.6-2.3)],['48×48 long rails',4,Math.max(0,L-4.6)],['48×48 short rails',4,Math.max(0,B-9.6-4.6)],['28×120 bottom boards',Math.max(1,Math.ceil((B-5)/12)),Math.max(0,L-5)],['23×48 long cladding',rows*2,L],['23×48 short cladding',rows*2,B],['23×48 top frame long (45°)',2,L],['23×48 top frame short (45°)',2,B]]}else{rows=Math.max(0,Math.floor((H-2.1+S)/(12+S)));items=[['48×48 posts/support',4,Math.max(0,H-9.6-2.1)],['48×48 long rails',4,Math.max(0,L-5.6)],['48×48 short rails',4,Math.max(0,B-5.6-9.6)],['28×120 bottom boards',Math.max(1,Math.ceil((B-6)/12)),Math.max(0,L-6)],['28×120 long cladding',rows*2,L],['28×120 short cladding',rows*2,Math.max(0,B-5.6)],['21×95 top frame long (45°)',2,L],['21×95 top frame short (45°)',2,B]]}$('cutList').innerHTML=items.map(([n,q,len])=>`<div class="cut-row"><span>${n}</span><b>${q} pcs × ${len.toFixed(1)} cm</b></div>`).join('')+`<div class="cut-row"><span>Cladding rows</span><b>${rows}</b></div>`}
document.addEventListener('click',e=>{const n=e.target.closest('[data-page]');if(n)nav(n.dataset.page);const g=e.target.closest('[data-go]');if(g)nav(g.dataset.go);const m=e.target.closest('[data-modal]');if(m){e.preventDefault();openModal(m.dataset.modal)}if(e.target.matches('[data-close]'))e.target.closest('dialog').close();if(e.target.id==='addExerciseBtn')addExercise();if(e.target.closest('.remove-exercise'))e.target.closest('.exercise-card').remove();if(e.target.closest('.add-set-v3'))addSet(e.target.closest('.exercise-card').querySelector('.sets-v3'));if(e.target.closest('.remove-set-v3')){const l=e.target.closest('.sets-v3');e.target.closest('.set-row-v3').remove();renumber(l)}const add=e.target.closest('[data-add-shopping]');if(add){$('shoppingItemForm').listId.value=add.dataset.addShopping;openModal('shoppingItemModal')}for(const key of ['task','workout','date','countdown','note','budget']){const el=e.target.closest(`[data-del-${key}]`);if(el){const plural={task:'tasks',workout:'workouts',date:'dates',countdown:'countdowns',note:'notes',budget:'budget'}[key];data[plural]=data[plural].filter(x=>x.id!==el.dataset['del'+key[0].toUpperCase()+key.slice(1)]);save('Deleted')}}const dl=e.target.closest('[data-del-shopping-list]');if(dl){data.shoppingLists=data.shoppingLists.filter(x=>x.id!==dl.dataset.delShoppingList);save('Deleted')}const di=e.target.closest('[data-del-shopping-item]');if(di){const l=data.shoppingLists.find(x=>x.id===di.dataset.listId);if(l){l.items=l.items.filter(x=>x.id!==di.dataset.delShoppingItem);save('Deleted')}}});
document.addEventListener('change',e=>{if(e.target.matches('[data-daily]')){const k=day(),id=e.target.dataset.daily;data.dailyDone[k]||=[];data.dailyDone[k]=e.target.checked?[...new Set([...data.dailyDone[k],id])]:data.dailyDone[k].filter(x=>x!==id);save()}if(e.target.matches('[data-task]')){const x=data.tasks.find(v=>v.id===e.target.dataset.task);if(x){x.done=e.target.checked;save()}}if(e.target.matches('[data-shopping-item]')){const l=data.shoppingLists.find(x=>x.id===e.target.dataset.listId),i=l?.items.find(x=>x.id===e.target.dataset.shoppingItem);if(i){i.done=e.target.checked;save()}}if(e.target.id==='chartExercise')renderCharts();if(['boxType','boxL','boxB','boxH','boxS'].includes(e.target.id))calculateBox()});
document.querySelectorAll('.filter').forEach(x=>x.onclick=()=>{filter=x.dataset.filter;document.querySelectorAll('.filter').forEach(y=>y.classList.toggle('active',y===x));renderTasks()});
const formData=f=>Object.fromEntries(new FormData(f).entries());
$('taskForm').onsubmit=e=>{e.preventDefault();data.tasks.push({id:crypto.randomUUID(),...formData(e.target),done:false,created:new Date().toISOString()});e.target.reset();e.target.closest('dialog').close();save('Task added')};
$('workoutForm').onsubmit=e=>{e.preventDefault();const v=formData(e.target),exercises=[...$('exerciseRows').children].map(card=>({name:card.querySelector('.exercise-name').value,sets:[...card.querySelectorAll('.set-row-v3')].map(r=>({weight:r.querySelector('.weight').value||'BW',reps:+r.querySelector('.reps').value||0})).filter(s=>s.reps>0)})).filter(x=>x.sets.length);if(!exercises.length){alert('Add at least one exercise with reps.');return}data.workouts.push({id:crypto.randomUUID(),...v,exercises,created:new Date().toISOString()});e.target.reset();e.target.closest('dialog').close();save('Workout saved')};
$('dateForm').onsubmit=e=>{e.preventDefault();data.dates.push({id:crypto.randomUUID(),...formData(e.target),recurring:e.target.recurring.checked});e.target.reset();e.target.closest('dialog').close();save('Date added')};
$('countdownForm').onsubmit=e=>{e.preventDefault();data.countdowns.push({id:crypto.randomUUID(),...formData(e.target)});e.target.reset();e.target.closest('dialog').close();save('Countdown added')};
$('shoppingListForm').onsubmit=e=>{e.preventDefault();const v=formData(e.target);data.shoppingLists.push({id:crypto.randomUUID(),title:v.title,items:[]});e.target.reset();e.target.closest('dialog').close();save('List created')};
$('shoppingItemForm').onsubmit=e=>{e.preventDefault();const v=formData(e.target),l=data.shoppingLists.find(x=>x.id===v.listId);if(l)l.items.push({id:crypto.randomUUID(),title:v.title,done:false});e.target.reset();e.target.closest('dialog').close();save('Item added')};
$('budgetForm').onsubmit=e=>{e.preventDefault();data.budget.push({id:crypto.randomUUID(),...formData(e.target),amount:+e.target.amount.value});e.target.reset();e.target.closest('dialog').close();save('Budget entry added')};
$('noteForm').onsubmit=e=>{e.preventDefault();data.notes.push({id:crypto.randomUUID(),...formData(e.target),created:new Date().toISOString()});e.target.reset();e.target.closest('dialog').close();save('Note saved')};
$('quick').onclick=()=>openModal('quickModal');$('resetSnus').onclick=()=>{if(confirm('Reset snus counter?')){data.snusStart=day();save('Reset')}};$('calcBtn').onclick=calculateBox;$('copyCut').onclick=()=>navigator.clipboard.writeText($('cutList').innerText).then(()=>toast('Copied'));
$('export').onclick=()=>{const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='dahlman-dashboard-backup-'+day()+'.json';a.click();URL.revokeObjectURL(a.href)};
$('import').onchange=async e=>{try{data=migrate(JSON.parse(await e.target.files[0].text()));save('Backup imported')}catch{alert('Could not read backup')}e.target.value=''};
window.addEventListener('resize',()=>setTimeout(renderCharts,100));render();initSync();